# Generated by Django 4.1.5 on 2023-01-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="data_add",
            new_name="date_add",
        ),
    ]
